version: '3.9'
services:
  clinico:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: assessmentDB
      DB_USERNAME: root
      DB_PASSWORD: root
    expose:
      - 9000
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/var/www/html
    ports:
      - 8001:80
    depends_on:
      clinico:
        condition: service_started
    entrypoint: /bin/sh -c "while ! nc -z clinico 9000; do sleep 1; done; nginx -g 'daemon off;'"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  mysql_data:
