version: '3.9'
services:
  clinico:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: assessmentDB
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    expose:
      - 9000
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/var/www/html
    ports:
      - 8001:80
    depends_on:
      - clinico
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  mysql_data:
